### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dgerhardt** [jbbarth/redmine_omniauth_cas#17]
I would like to use your CAS plugin for my organization's Redmine installation but unfortunately can't since there is no licensing information. Could you please add a LICENSE file to the repo?

Thank you very much!

Edit: I guess it's the same as Redmine but a clarification wouldn't harm.

**Comment by jbbarth** [comment]
I'll do that immediately no problem. This project is released under the MIT license like much of my work, this should be permissive enough for you to use it in any case.

**Comment by dgerhardt** [comment]
Thank you for the fast reaction and the work on this plugin.
