### ISSUE TITLE
Compatibility with redmine 5.0

### ISSUE THREAD

**Issue by alexandrebapseres** [jbbarth/redmine_omniauth_cas#26]
Hi, 
Is this plugin intended to work with redmine 5.0 ?
We would like to continue to use both CAS and redmine authentication and this plugin is the only one that allows us this.
Thank you

**Comment by nanego** [comment]
Hello
Yes, we plan to update this plugin. I hope we can accomplish it by the end of the year.

**Comment by alexandrebapseres** [comment]
Ok, 
Thanks a lot
