### ISSUE TITLE
undefined method `cas_host' for class `OmniAuth::Strategies::CAS'

### ISSUE THREAD

**Issue by madhippie** [jbbarth/redmine_omniauth_cas#9]
Hi there,

first of all: thanks for this great plugin!

Unfortunately, after migrating my Redmine 2.2 Installation to a Server running Ruby 1.9.3 and Rails 3.2.13, I get the following error:

undefined method `cas_host' for class `OmniAuth::Strategies::CAS'
/home/rails/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/home/rails/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'

Is this an issue with with my activesupport gem?

**Comment by shadowbq** [comment]
Stale.. saw this issue .. was there a resolution?

**Comment by jbbarth** [comment]
See above, there was a breaking change above omniauth-cas 1.0.1 so I locked the version in the Gemfile. This can be closed I think...
